### ISSUE TITLE
Missing groupEntityType in IdentitySource

### ISSUE THREAD

**Issue by mrbrianevans** [cdklabs/cdk-verified-permissions#103]
Many thanks for this library! Hope it gets merged into cdk master at some point.

The construct for IdentitySource is missing props to configure the group settings. 

See https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CognitoUserPoolConfiguration.html ` groupConfiguration ` and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-verifiedpermissions-identitysource-cognitogroupconfiguration.html

The construct currently supports setting principalEntityType but not group.

This is what the setting looks like in the console:
![image](https://github.com/cdklabs/cdk-verified-permissions/assets/53117772/cf426724-d031-4bb0-960f-00f6e335cd37)

We need a prop to specify what entity type cognito groups are.

**Comment by reste85** [comment]
@mrbrianevans released in [v0.0.1-alpha.8](https://github.com/cdklabs/cdk-verified-permissions/releases/tag/v0.0.1-alpha.8)
