### ISSUE TITLE
`validatePolicy()` does not output useful errors / warnings

### ISSUE THREAD

**Issue by joshkraft** [cdklabs/cdk-verified-permissions#268]
# Description

When policies are validated using the `validatePolicy()` function, the error / warning messages are intended to display specific details from the validation process.

However, they currently output as [object Object] instead of showing useful information. This issue appears to stem from how error objects are converted to strings in the `validatePolicy()` function.

# Steps to Reproduce

1. Trigger a policy validation that fails or generates errors using `validatePolicy()`.

2. Observe the output error message, which does not display the expected text of the errors. Instead, it displays something like:

```
Policy {{POLICY_CONTENTS}} could not be parsed: [object Object]; [object Object]
```

**Comment by reste85** [comment]
Thanks @joshkraft , taking a look

**Comment by reste85** [comment]
@joshkraft  fix will be merged soon, thank you!
